### ISSUE TITLE
Your recent commits broke something

### ISSUE THREAD

**Issue by larryranches** [iZaL/insta-snap#2]
![screen_shot](https://cloud.githubusercontent.com/assets/191961/15062630/c61b9380-12f6-11e6-81a6-a10711a28f73.png)

![simulator screen shot may 5 2016 7 33 17 pm](https://cloud.githubusercontent.com/assets/191961/15062765/487c65b0-12f8-11e6-8716-95544b64994c.png)

**Comment by iZaL** [comment]
should work now..
